### ISSUE TITLE
Desired projects numbering

### ISSUE THREAD

**Issue by WesleyTheGeolien** [ClimateMatchAcademy/course-content#95]
Desired layout by @zanemit :
```
- chapters:
  - file: projects/README.md
    title: Introduction
  - file: projects/docs/project_guidance.md
  - file: projects/docs/datasets_overview.md
    sections:
    - file: projects/project-notebooks/Sea level rise.ipynb
    - file: projects/project-notebooks/Regional precipitation variability.ipynb
    - file: projects/project-notebooks/Surface albedo and land use.ipynb
    - file: projects/project-notebooks/Wildfires and burnt areas.ipynb
    - file: projects/project-notebooks/Ocean acidification.ipynb
    - file: projects/project-notebooks/ENSO impact on precipitation and temperature.ipynb
    - file: projects/project-notebooks/Heatwaves.ipynb
  - file: projects/docs/continuing_your_project_after_the_course.md
  part: Project Booklet
```
